resolver: lts-23.18
packages:
- '.'

ghc-options:
  "$locals": -O2 -fspecialize-aggressively -fexpose-all-unfoldings

extra-deps:
- github: purescript/purescript
  commit: 8ac0fb2962a7df318a74216872465dc2868c6064

- language-javascript-0.7.0.0
- bower-json-1.1.0.0
- these-1.2.1
- aeson-better-errors-0.9.1.3

- github: purescript/cheapskate
  commit: 633c69024e061ad956f1aecfc137fb99a7a7a20b

nix:
  packages:
  - zlib

flags:
  aeson-pretty:
    lib-only: true
